// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619180904_CreateDatabaseSchema")]
    partial class CreateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.ActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUser")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("MomId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ActionIt__3214EC075939225A");

                    b.HasIndex("AssignedToUser");

                    b.HasIndex("MomId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("WebApi.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Attendee__3214EC0742BA997C");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("WebApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookedByUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__3214EC0779CC90C6");

                    b.HasIndex("BookedByUser");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebApi.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UploadedByUser")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Files__3214EC07FF1D0383");

                    b.HasIndex("MomId");

                    b.HasIndex("UploadedByUser");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("WebApi.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agenda")
                        .HasColumnType("text");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduledByUser")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Meetings__3214EC07F9BFBF19");

                    b.HasIndex("BookingId");

                    b.HasIndex("ScheduledByUser");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("WebApi.Models.MinutesOfMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUser")
                        .HasColumnType("int");

                    b.Property<string>("Decisions")
                        .HasColumnType("text");

                    b.Property<string>("DiscussionPoints")
                        .HasColumnType("text");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeCreation")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__MinutesO__3214EC0747022633");

                    b.HasIndex("CreatedByUser");

                    b.HasIndex("MeetingId");

                    b.ToTable("MinutesOfMeeting", (string)null);
                });

            modelBuilder.Entity("WebApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionItemId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC079935D12E");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebApi.Models.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Rooms__3214EC076CEDDA64");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.ActionItem", b =>
                {
                    b.HasOne("WebApi.Models.User", "AssignedToUserNavigation")
                        .WithMany("ActionItems")
                        .HasForeignKey("AssignedToUser")
                        .HasConstraintName("FK__ActionIte__Assig__73BA3083");

                    b.HasOne("WebApi.Models.MinutesOfMeeting", "Mom")
                        .WithMany("ActionItems")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK__ActionIte__MomId__72C60C4A");

                    b.Navigation("AssignedToUserNavigation");

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("WebApi.Models.Attendee", b =>
                {
                    b.HasOne("WebApi.Models.Meeting", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .HasConstraintName("FK__Attendees__Meeti__68487DD7");

                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany("Attendees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Attendees__UserI__6754599E");

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.Booking", b =>
                {
                    b.HasOne("WebApi.Models.User", "BookedByUserNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("BookedByUser")
                        .HasConstraintName("FK__Bookings__Booked__60A75C0F");

                    b.HasOne("WebApi.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__Bookings__RoomId__5FB337D6");

                    b.Navigation("BookedByUserNavigation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebApi.Models.File", b =>
                {
                    b.HasOne("WebApi.Models.MinutesOfMeeting", "Mom")
                        .WithMany("Files")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK__Files__MomId__6EF57B66");

                    b.HasOne("WebApi.Models.User", "UploadedByUserNavigation")
                        .WithMany("Files")
                        .HasForeignKey("UploadedByUser")
                        .HasConstraintName("FK__Files__UploadedB__6FE99F9F");

                    b.Navigation("Mom");

                    b.Navigation("UploadedByUserNavigation");
                });

            modelBuilder.Entity("WebApi.Models.Meeting", b =>
                {
                    b.HasOne("WebApi.Models.Booking", "Booking")
                        .WithMany("Meetings")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Meetings__Bookin__6383C8BA");

                    b.HasOne("WebApi.Models.User", "ScheduledByUserNavigation")
                        .WithMany("Meetings")
                        .HasForeignKey("ScheduledByUser")
                        .HasConstraintName("FK__Meetings__Schedu__6477ECF3");

                    b.Navigation("Booking");

                    b.Navigation("ScheduledByUserNavigation");
                });

            modelBuilder.Entity("WebApi.Models.MinutesOfMeeting", b =>
                {
                    b.HasOne("WebApi.Models.User", "CreatedByUserNavigation")
                        .WithMany("MinutesOfMeetings")
                        .HasForeignKey("CreatedByUser")
                        .HasConstraintName("FK__MinutesOf__Creat__6C190EBB");

                    b.HasOne("WebApi.Models.Meeting", "Meeting")
                        .WithMany("MinutesOfMeetings")
                        .HasForeignKey("MeetingId")
                        .HasConstraintName("FK__MinutesOf__Meeti__6B24EA82");

                    b.Navigation("CreatedByUserNavigation");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("WebApi.Models.Notification", b =>
                {
                    b.HasOne("WebApi.Models.ActionItem", "ActionItem")
                        .WithMany("Notifications")
                        .HasForeignKey("ActionItemId")
                        .HasConstraintName("FK__Notificat__Actio__778AC167");

                    b.HasOne("WebApi.Models.Meeting", "Meeting")
                        .WithMany("Notifications")
                        .HasForeignKey("MeetingId")
                        .HasConstraintName("FK__Notificat__Meeti__76969D2E");

                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__787EE5A0");

                    b.Navigation("ActionItem");

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.ActionItem", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("WebApi.Models.Booking", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("WebApi.Models.Meeting", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("MinutesOfMeetings");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("WebApi.Models.MinutesOfMeeting", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("WebApi.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Attendees");

                    b.Navigation("Bookings");

                    b.Navigation("Files");

                    b.Navigation("Meetings");

                    b.Navigation("MinutesOfMeetings");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
